language: objective-c

podfile: Example/Podfile
osx_image: xcode7

before_install:
- gem install cocoapods xcpretty --no-ri --no-rdoc

script:
- set -o pipefail && xcodebuild -workspace Example/TouchIDAuth.xcworkspace -scheme TouchID -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c

branches:
  only:
  - master

notifications:
  slack:
    secure: FYTAD2dSWOSaIV9f2c+3RmX5ib+aJuTioNAq+RGK3S9dbmBgRDuPainIbtZX5uDBWkTHDaVe6ydELB+HLkt8zccGjU9Rc8n1HQqn86QjGQXFxnCILMrUQu0utzHgXGy6XDCVkO6pCGHPw0GCes2KUZ7JyohJz2tx1aOLxI0DC4E=
