# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

podfile: Example/Podfile

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem install cocoapods --no-ri --no-rdoc

script:
  - xctool -workspace Example/TouchIDAuth.xcworkspace -scheme TouchIDAuth -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean test

branches:
  only:
    - master

